services:
  mysql:
    image: mysql:8.4
    container_name: pm_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: password_manager
    ports:
      - "3306:3306"
    command: ["--default-authentication-plugin=mysql_native_password"]
    volumes:
      - pm_mysql_data:/var/lib/mysql

volumes:
  pm_mysql_data:
